/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoVirtualGridRouteImport } from './routes/demo-virtual-grid'
import { Route as DemoVboxLayoutRouteImport } from './routes/demo-vbox-layout'
import { Route as DemoSupportTicketRouteImport } from './routes/demo-support-ticket'
import { Route as DemoRegistrationRouteImport } from './routes/demo-registration'
import { Route as DemoOrdersRouteImport } from './routes/demo-orders'
import { Route as DemoMultiSelectRouteImport } from './routes/demo-multi-select'
import { Route as DemoHboxLayoutRouteImport } from './routes/demo-hbox-layout'
import { Route as DemoGridRouteImport } from './routes/demo-grid'
import { Route as DemoFormWizardRouteImport } from './routes/demo-form-wizard'
import { Route as DemoFormRouteImport } from './routes/demo-form'
import { Route as DemoDatePickerRouteImport } from './routes/demo-date-picker'
import { Route as DemoColumnReorderingRouteImport } from './routes/demo-column-reordering'
import { Route as DemoCardLayoutRouteImport } from './routes/demo-card-layout'
import { Route as DemoBorderLayoutRouteImport } from './routes/demo-border-layout'
import { Route as DemoAccordionLayoutRouteImport } from './routes/demo-accordion-layout'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'

const DemoVirtualGridRoute = DemoVirtualGridRouteImport.update({
  id: '/demo-virtual-grid',
  path: '/demo-virtual-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoVboxLayoutRoute = DemoVboxLayoutRouteImport.update({
  id: '/demo-vbox-layout',
  path: '/demo-vbox-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSupportTicketRoute = DemoSupportTicketRouteImport.update({
  id: '/demo-support-ticket',
  path: '/demo-support-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRegistrationRoute = DemoRegistrationRouteImport.update({
  id: '/demo-registration',
  path: '/demo-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrdersRoute = DemoOrdersRouteImport.update({
  id: '/demo-orders',
  path: '/demo-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMultiSelectRoute = DemoMultiSelectRouteImport.update({
  id: '/demo-multi-select',
  path: '/demo-multi-select',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoHboxLayoutRoute = DemoHboxLayoutRouteImport.update({
  id: '/demo-hbox-layout',
  path: '/demo-hbox-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGridRoute = DemoGridRouteImport.update({
  id: '/demo-grid',
  path: '/demo-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormWizardRoute = DemoFormWizardRouteImport.update({
  id: '/demo-form-wizard',
  path: '/demo-form-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo-form',
  path: '/demo-form',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDatePickerRoute = DemoDatePickerRouteImport.update({
  id: '/demo-date-picker',
  path: '/demo-date-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoColumnReorderingRoute = DemoColumnReorderingRouteImport.update({
  id: '/demo-column-reordering',
  path: '/demo-column-reordering',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCardLayoutRoute = DemoCardLayoutRouteImport.update({
  id: '/demo-card-layout',
  path: '/demo-card-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBorderLayoutRoute = DemoBorderLayoutRouteImport.update({
  id: '/demo-border-layout',
  path: '/demo-border-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAccordionLayoutRoute = DemoAccordionLayoutRouteImport.update({
  id: '/demo-accordion-layout',
  path: '/demo-accordion-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/demo-accordion-layout': typeof DemoAccordionLayoutRoute
  '/demo-border-layout': typeof DemoBorderLayoutRoute
  '/demo-card-layout': typeof DemoCardLayoutRoute
  '/demo-column-reordering': typeof DemoColumnReorderingRoute
  '/demo-date-picker': typeof DemoDatePickerRoute
  '/demo-form': typeof DemoFormRoute
  '/demo-form-wizard': typeof DemoFormWizardRoute
  '/demo-grid': typeof DemoGridRoute
  '/demo-hbox-layout': typeof DemoHboxLayoutRoute
  '/demo-multi-select': typeof DemoMultiSelectRoute
  '/demo-orders': typeof DemoOrdersRoute
  '/demo-registration': typeof DemoRegistrationRoute
  '/demo-support-ticket': typeof DemoSupportTicketRoute
  '/demo-vbox-layout': typeof DemoVboxLayoutRoute
  '/demo-virtual-grid': typeof DemoVirtualGridRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/demo-accordion-layout': typeof DemoAccordionLayoutRoute
  '/demo-border-layout': typeof DemoBorderLayoutRoute
  '/demo-card-layout': typeof DemoCardLayoutRoute
  '/demo-column-reordering': typeof DemoColumnReorderingRoute
  '/demo-date-picker': typeof DemoDatePickerRoute
  '/demo-form': typeof DemoFormRoute
  '/demo-form-wizard': typeof DemoFormWizardRoute
  '/demo-grid': typeof DemoGridRoute
  '/demo-hbox-layout': typeof DemoHboxLayoutRoute
  '/demo-multi-select': typeof DemoMultiSelectRoute
  '/demo-orders': typeof DemoOrdersRoute
  '/demo-registration': typeof DemoRegistrationRoute
  '/demo-support-ticket': typeof DemoSupportTicketRoute
  '/demo-vbox-layout': typeof DemoVboxLayoutRoute
  '/demo-virtual-grid': typeof DemoVirtualGridRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/demo-accordion-layout': typeof DemoAccordionLayoutRoute
  '/demo-border-layout': typeof DemoBorderLayoutRoute
  '/demo-card-layout': typeof DemoCardLayoutRoute
  '/demo-column-reordering': typeof DemoColumnReorderingRoute
  '/demo-date-picker': typeof DemoDatePickerRoute
  '/demo-form': typeof DemoFormRoute
  '/demo-form-wizard': typeof DemoFormWizardRoute
  '/demo-grid': typeof DemoGridRoute
  '/demo-hbox-layout': typeof DemoHboxLayoutRoute
  '/demo-multi-select': typeof DemoMultiSelectRoute
  '/demo-orders': typeof DemoOrdersRoute
  '/demo-registration': typeof DemoRegistrationRoute
  '/demo-support-ticket': typeof DemoSupportTicketRoute
  '/demo-vbox-layout': typeof DemoVboxLayoutRoute
  '/demo-virtual-grid': typeof DemoVirtualGridRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/demo-accordion-layout'
    | '/demo-border-layout'
    | '/demo-card-layout'
    | '/demo-column-reordering'
    | '/demo-date-picker'
    | '/demo-form'
    | '/demo-form-wizard'
    | '/demo-grid'
    | '/demo-hbox-layout'
    | '/demo-multi-select'
    | '/demo-orders'
    | '/demo-registration'
    | '/demo-support-ticket'
    | '/demo-vbox-layout'
    | '/demo-virtual-grid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/demo-accordion-layout'
    | '/demo-border-layout'
    | '/demo-card-layout'
    | '/demo-column-reordering'
    | '/demo-date-picker'
    | '/demo-form'
    | '/demo-form-wizard'
    | '/demo-grid'
    | '/demo-hbox-layout'
    | '/demo-multi-select'
    | '/demo-orders'
    | '/demo-registration'
    | '/demo-support-ticket'
    | '/demo-vbox-layout'
    | '/demo-virtual-grid'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/demo-accordion-layout'
    | '/demo-border-layout'
    | '/demo-card-layout'
    | '/demo-column-reordering'
    | '/demo-date-picker'
    | '/demo-form'
    | '/demo-form-wizard'
    | '/demo-grid'
    | '/demo-hbox-layout'
    | '/demo-multi-select'
    | '/demo-orders'
    | '/demo-registration'
    | '/demo-support-ticket'
    | '/demo-vbox-layout'
    | '/demo-virtual-grid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DemoAccordionLayoutRoute: typeof DemoAccordionLayoutRoute
  DemoBorderLayoutRoute: typeof DemoBorderLayoutRoute
  DemoCardLayoutRoute: typeof DemoCardLayoutRoute
  DemoColumnReorderingRoute: typeof DemoColumnReorderingRoute
  DemoDatePickerRoute: typeof DemoDatePickerRoute
  DemoFormRoute: typeof DemoFormRoute
  DemoFormWizardRoute: typeof DemoFormWizardRoute
  DemoGridRoute: typeof DemoGridRoute
  DemoHboxLayoutRoute: typeof DemoHboxLayoutRoute
  DemoMultiSelectRoute: typeof DemoMultiSelectRoute
  DemoOrdersRoute: typeof DemoOrdersRoute
  DemoRegistrationRoute: typeof DemoRegistrationRoute
  DemoSupportTicketRoute: typeof DemoSupportTicketRoute
  DemoVboxLayoutRoute: typeof DemoVboxLayoutRoute
  DemoVirtualGridRoute: typeof DemoVirtualGridRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo-virtual-grid': {
      id: '/demo-virtual-grid'
      path: '/demo-virtual-grid'
      fullPath: '/demo-virtual-grid'
      preLoaderRoute: typeof DemoVirtualGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-vbox-layout': {
      id: '/demo-vbox-layout'
      path: '/demo-vbox-layout'
      fullPath: '/demo-vbox-layout'
      preLoaderRoute: typeof DemoVboxLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-support-ticket': {
      id: '/demo-support-ticket'
      path: '/demo-support-ticket'
      fullPath: '/demo-support-ticket'
      preLoaderRoute: typeof DemoSupportTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-registration': {
      id: '/demo-registration'
      path: '/demo-registration'
      fullPath: '/demo-registration'
      preLoaderRoute: typeof DemoRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-orders': {
      id: '/demo-orders'
      path: '/demo-orders'
      fullPath: '/demo-orders'
      preLoaderRoute: typeof DemoOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-multi-select': {
      id: '/demo-multi-select'
      path: '/demo-multi-select'
      fullPath: '/demo-multi-select'
      preLoaderRoute: typeof DemoMultiSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-hbox-layout': {
      id: '/demo-hbox-layout'
      path: '/demo-hbox-layout'
      fullPath: '/demo-hbox-layout'
      preLoaderRoute: typeof DemoHboxLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-grid': {
      id: '/demo-grid'
      path: '/demo-grid'
      fullPath: '/demo-grid'
      preLoaderRoute: typeof DemoGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-form-wizard': {
      id: '/demo-form-wizard'
      path: '/demo-form-wizard'
      fullPath: '/demo-form-wizard'
      preLoaderRoute: typeof DemoFormWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-form': {
      id: '/demo-form'
      path: '/demo-form'
      fullPath: '/demo-form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-date-picker': {
      id: '/demo-date-picker'
      path: '/demo-date-picker'
      fullPath: '/demo-date-picker'
      preLoaderRoute: typeof DemoDatePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-column-reordering': {
      id: '/demo-column-reordering'
      path: '/demo-column-reordering'
      fullPath: '/demo-column-reordering'
      preLoaderRoute: typeof DemoColumnReorderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-card-layout': {
      id: '/demo-card-layout'
      path: '/demo-card-layout'
      fullPath: '/demo-card-layout'
      preLoaderRoute: typeof DemoCardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-border-layout': {
      id: '/demo-border-layout'
      path: '/demo-border-layout'
      fullPath: '/demo-border-layout'
      preLoaderRoute: typeof DemoBorderLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-accordion-layout': {
      id: '/demo-accordion-layout'
      path: '/demo-accordion-layout'
      fullPath: '/demo-accordion-layout'
      preLoaderRoute: typeof DemoAccordionLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DemoAccordionLayoutRoute: DemoAccordionLayoutRoute,
  DemoBorderLayoutRoute: DemoBorderLayoutRoute,
  DemoCardLayoutRoute: DemoCardLayoutRoute,
  DemoColumnReorderingRoute: DemoColumnReorderingRoute,
  DemoDatePickerRoute: DemoDatePickerRoute,
  DemoFormRoute: DemoFormRoute,
  DemoFormWizardRoute: DemoFormWizardRoute,
  DemoGridRoute: DemoGridRoute,
  DemoHboxLayoutRoute: DemoHboxLayoutRoute,
  DemoMultiSelectRoute: DemoMultiSelectRoute,
  DemoOrdersRoute: DemoOrdersRoute,
  DemoRegistrationRoute: DemoRegistrationRoute,
  DemoSupportTicketRoute: DemoSupportTicketRoute,
  DemoVboxLayoutRoute: DemoVboxLayoutRoute,
  DemoVirtualGridRoute: DemoVirtualGridRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
