/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoSupportTicketRouteImport } from './routes/demo-support-ticket'
import { Route as DemoRegistrationRouteImport } from './routes/demo-registration'
import { Route as DemoOrdersRouteImport } from './routes/demo-orders'
import { Route as DemoGridRouteImport } from './routes/demo-grid'
import { Route as DemoFormRouteImport } from './routes/demo-form'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'

const DemoSupportTicketRoute = DemoSupportTicketRouteImport.update({
  id: '/demo-support-ticket',
  path: '/demo-support-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRegistrationRoute = DemoRegistrationRouteImport.update({
  id: '/demo-registration',
  path: '/demo-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrdersRoute = DemoOrdersRouteImport.update({
  id: '/demo-orders',
  path: '/demo-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGridRoute = DemoGridRouteImport.update({
  id: '/demo-grid',
  path: '/demo-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo-form',
  path: '/demo-form',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/demo-form': typeof DemoFormRoute
  '/demo-grid': typeof DemoGridRoute
  '/demo-orders': typeof DemoOrdersRoute
  '/demo-registration': typeof DemoRegistrationRoute
  '/demo-support-ticket': typeof DemoSupportTicketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/demo-form': typeof DemoFormRoute
  '/demo-grid': typeof DemoGridRoute
  '/demo-orders': typeof DemoOrdersRoute
  '/demo-registration': typeof DemoRegistrationRoute
  '/demo-support-ticket': typeof DemoSupportTicketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/demo-form': typeof DemoFormRoute
  '/demo-grid': typeof DemoGridRoute
  '/demo-orders': typeof DemoOrdersRoute
  '/demo-registration': typeof DemoRegistrationRoute
  '/demo-support-ticket': typeof DemoSupportTicketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/demo-form'
    | '/demo-grid'
    | '/demo-orders'
    | '/demo-registration'
    | '/demo-support-ticket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/demo-form'
    | '/demo-grid'
    | '/demo-orders'
    | '/demo-registration'
    | '/demo-support-ticket'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/demo-form'
    | '/demo-grid'
    | '/demo-orders'
    | '/demo-registration'
    | '/demo-support-ticket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DemoFormRoute: typeof DemoFormRoute
  DemoGridRoute: typeof DemoGridRoute
  DemoOrdersRoute: typeof DemoOrdersRoute
  DemoRegistrationRoute: typeof DemoRegistrationRoute
  DemoSupportTicketRoute: typeof DemoSupportTicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo-support-ticket': {
      id: '/demo-support-ticket'
      path: '/demo-support-ticket'
      fullPath: '/demo-support-ticket'
      preLoaderRoute: typeof DemoSupportTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-registration': {
      id: '/demo-registration'
      path: '/demo-registration'
      fullPath: '/demo-registration'
      preLoaderRoute: typeof DemoRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-orders': {
      id: '/demo-orders'
      path: '/demo-orders'
      fullPath: '/demo-orders'
      preLoaderRoute: typeof DemoOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-grid': {
      id: '/demo-grid'
      path: '/demo-grid'
      fullPath: '/demo-grid'
      preLoaderRoute: typeof DemoGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-form': {
      id: '/demo-form'
      path: '/demo-form'
      fullPath: '/demo-form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DemoFormRoute: DemoFormRoute,
  DemoGridRoute: DemoGridRoute,
  DemoOrdersRoute: DemoOrdersRoute,
  DemoRegistrationRoute: DemoRegistrationRoute,
  DemoSupportTicketRoute: DemoSupportTicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
