#!/usr/bin/env node

// NOTE: Changeset check — verifies changeset exists when core package files change.
// NOTE: Checks if a changeset is required when core package files change.

import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { getChangedFiles } from "../shared/git-files.mjs";

/**
 * NOTE: Checks if a changeset is required and exists. Auto-generates if possible.
 * @param {string} workspaceRoot - Project root directory
 * @param {{ scope?: string, extensions?: string }} config - Scope and extension filters
 * @returns {{ passed: boolean, output?: string }}
 */
export function checkChangeset(workspaceRoot, config = {}) {
	const scope = config.scope || "packages/core/src/**";
	const extensions = config.extensions || "ts tsx";

	const changedFiles = getChangedFiles(workspaceRoot);
	const scopePattern = scope.replace("/**", "").replace("**", "");
	const coreChanged = changedFiles.some((f) => {
		const matchesScope = f.includes(scopePattern.replace("/**", ""));
		const ext = f.split(".").pop();
		return matchesScope && extensions.includes(ext);
	});

	if (!coreChanged) return { passed: true };

	const changesetDir = join(workspaceRoot, ".changeset");
	if (!existsSync(changesetDir)) {
		return tryAutoGenerate(changesetDir);
	}

	const changesetFiles = readdirSync(changesetDir).filter(
		(f) => f.endsWith(".md") && f !== "README.md" && f !== "config.json",
	);

	if (changesetFiles.length > 0) return { passed: true };

	return tryAutoGenerate(changesetDir);
}

/**
 * NOTE: Attempts to auto-generate a changeset file.
 */
function tryAutoGenerate(changesetDir) {
	try {
		if (!existsSync(changesetDir)) {
			return {
				passed: false,
				output:
					"Changeset required: packages/core/src/ files changed but no .changeset/ directory found. Run `pnpm changeset` to create one.",
			};
		}
		const autoFile = join(changesetDir, "auto-compliance.md");
		writeFileSync(
			autoFile,
			'---\n"schema-framework": patch\n---\n\nAuto-generated by compliance check\n',
		);
		return { passed: true, output: "Auto-generated changeset file" };
	} catch {
		return {
			passed: false,
			output:
				"Changeset required: packages/core/src/ files changed. Run `pnpm changeset` to create one.",
		};
	}
}
